env:
  - CGO_ENABLED=0
builds:
  - id: rport
    main: ./cmd/rport
    binary: rport
    ldflags:
      - -s -w -X github.com/cloudradar-monitoring/rport/share.BuildVersion={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - mips64p32
      - mips64p32le
      - ppc
      - s390
      - s390x
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
  - id: rportd
    main: ./cmd/rportd
    binary: rportd
    ldflags:
      - -s -w -X github.com/cloudradar-monitoring/rport/share.BuildVersion={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - mips64p32
      - mips64p32le
      - ppc
      - s390
      - s390x
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc

