name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: rport and rportd
    runs-on: ubuntu-latest
    # TODO(m-terel): consider to run all ssh commands at once if current execution would be overhead
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=`date -u +%d-%m-%Y.%H:%M:%S`-sha:`git rev-parse HEAD`'"  -o ./ ./cmd/...

      - name: Stop rport server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: service rportd stop

      - name: Copy a new version to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "rportd,rport"
          target: ${{ secrets.DEPLOY_FOLDER }}

      - name: Start rport server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: service rportd start
