name: Go
on: [push]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: go mod vendor
        run: go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.17
          args: -c .golangci.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
