name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 is required for the change log to work correctly.
          # For the details please see https://goreleaser.com/ci/actions/
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run GoReleaser for Rport Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Rport Build Commit Info
        id: rport_commit_info
        run: |
          echo ::set-output name=commit_sha::$(git rev-parse HEAD)
      - name: Checkout Rport Plus
        uses: actions/checkout@v3
        with:
          repository: cloudradar-monitoring/rport-plus
          ref: ${{github.ref_name}}
          ssh-key: ${{ secrets.RPORT_PLUS_PRIV_KEY }}
          path: rport-plus
      - name: Build Rport Plus
        id: rport_plus_build
        run: |
          pwd
          cd rport-plus
          echo ::set-output name=repo_name::$(basename `git rev-parse --show-toplevel`)
          make build
        env:
          RPORT_GIT_REF: ${{github.ref_name}}
          RPORT_COMMIT_ID: ${{ steps.rport_commit_info.outputs.commit_sha }}
      - name: Compress Rport Plus Release Assets
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            rport-plus/README.md
            rport-plus/license.txt
            rport-plus/rport-plus.so
          outPath: rport-plus/${{ steps.rport_plus_build.outputs.repo_name }}_${{github.ref_name}}_Linux_x86_64.tar.gz
      - name: Release Rport Plus
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{github.ref_name}}-${{ steps.rport_plus_build.outputs.repo_name }}"
          prerelease: true
          draft: true
          files: |
            rport-plus/${{ steps.rport_plus_build.outputs.repo_name }}_${{github.ref_name}}_Linux_x86_64.tar.gz
