name: Test Server/Client Nix
on: [push]
jobs:
  test:
    name: Test Server/Client Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: go test -race -v ./...
