name: Deploy
on: [push]

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        # set rport version to {date-time}-{github-master-head-sha}
        run: go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=$(date -u +%y.%m%d.%H%M)-$(git rev-parse HEAD)'"  -o ./ ./cmd/...

      - name: Test Build
        shell: bash
        run: |
            .github/scripts/start_rportd.sh
            .github/scripts/start_rport.sh